# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PhotoView360
                                 A QGIS plugin
 A QGIS plugin for viewing georeferenced 360-degree panoramic images.

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-31
        copyright            : (C) 2026 by Rei Ito
        email                : katzchen.th@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PhotoView360 class from file PhotoView360.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .photoview360 import PhotoView360
    return PhotoView360(iface)
